version: "3"

services:
  ask_client:
    build:
      context: client
    ports:
      - 4000:80
    networks:
      - frontend
    depends_on:
      - api-server
  api-server:
    build:
      context: server
    env_file:
      - server/.env
    networks:
      - frontend
      - backend
    depends_on:
      - ask_db
  ask_db:
    build:
      context: db
    env_file:
      - db/.env
    networks:
      - backend
    volumes:
      - db_vol:/var/lib/mysql

volumes:
  db_vol:

networks:
  frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.58.97.0/24
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.38.97.0/24
